# Generated by Django 5.2.17 on 2026-09-25 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process', models.CharField(max_length=64)),
                ('sha256', models.CharField(max_length=64)),
                ('source_description', models.CharField(max_length=500)),
                ('raw_csv', models.BinaryField()),
                ('rows', models.JSONField()),
                ('parser_version', models.PositiveSmallIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'process', 'sha256', 'parser_version'), name='unique_project_operation_log')],
            },
        ),
    ]
