# Generated by Django 5.2.17 on 2026-09-25 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_operationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operationlog',
            name='unique_project_operation_log',
        ),
        migrations.AddField(
            model_name='operationlog',
            name='period_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='period_start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name='operationlog',
            constraint=models.UniqueConstraint(fields=('project', 'process', 'sha256', 'parser_version', 'period_start_at', 'period_end_at'), name='unique_project_operation_log'),
        ),
    ]
