# Generated by Django 5.2.17 on 2026-09-25 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_availabilityplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ledger_version', models.PositiveSmallIntegerField()),
                ('input_snapshot', models.JSONField()),
                ('ledger', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('availability_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.availabilityplan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operation_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.operationlog')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='projects.project')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectrevision')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('revision', 'operation_log', 'availability_plan', 'ledger_version'), name='unique_simulation_run_inputs')],
            },
        ),
    ]
