# Generated by Django 5.2.17 on 2026-09-25 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_simulationrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_csv', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('metadata_sha256', models.CharField(max_length=64)),
                ('source_description', models.CharField(max_length=500)),
                ('forecast_basis', models.CharField(max_length=1000)),
                ('horizon_months', models.PositiveSmallIntegerField()),
                ('monthly_discount_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('discount_rate_source', models.CharField(max_length=500)),
                ('parser_version', models.PositiveSmallIntegerField()),
                ('rows', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_plans', to='projects.project')),
                ('simulation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_plans', to='projects.simulationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('simulation_run', 'sha256', 'metadata_sha256', 'horizon_months', 'monthly_discount_rate', 'parser_version'), name='unique_finance_plan_inputs')],
            },
        ),
    ]
