# Generated by Django 5.2.17 on 2026-09-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_financeplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeplan',
            name='source_filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
