# Generated by Django 5.2.17 on 2026-09-25 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_financeplan_source_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=22)),
                ('source_date', models.DateField()),
                ('source_ref', models.CharField(max_length=1000)),
                ('checksum', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='projects.financeplan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base_plan', 'checksum'), name='unique_finance_variant_inputs')],
            },
        ),
    ]
