# Generated by Django 5.2.17 on 2026-09-26 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_financevariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityplan',
            name='selection_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='availabilityplan',
            name='robot_record_index',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveConstraint(
            model_name='availabilityplan',
            name='unique_project_availability_plan',
        ),
        migrations.AddConstraint(
            model_name='availabilityplan',
            constraint=models.UniqueConstraint(condition=models.Q(selection_key__isnull=True), fields=('project', 'operation_log', 'process', 'robot_record_index', 'fleet', 'sha256', 'parser_version'), name='unique_project_availability_plan'),
        ),
        migrations.AddConstraint(
            model_name='availabilityplan',
            constraint=models.UniqueConstraint(fields=('project', 'operation_log', 'process', 'selection_key', 'fleet', 'sha256', 'parser_version'), name='unique_project_availability_selection'),
        ),
        migrations.AddConstraint(
            model_name='availabilityplan',
            constraint=models.CheckConstraint(condition=models.Q(('robot_record_index__isnull', False), ('selection_key__isnull', False), _connector='OR'), name='availability_has_robot_identity'),
        ),
    ]
