# Generated by Django 5.2.17 on 2026-09-28 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_simulationrun_resource_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=40)),
                ('filename', models.CharField(max_length=255)),
                ('source_description', models.CharField(max_length=500)),
                ('original_sha256', models.CharField(max_length=64)),
                ('png_sha256', models.CharField(max_length=64)),
                ('image_png', models.BinaryField()),
                ('width_px', models.PositiveIntegerField()),
                ('height_px', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_sources', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
