# Generated by Django 5.2.17 on 2026-09-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('source_label', models.CharField(max_length=100)),
                ('source_kind', models.CharField(choices=[('organizer_v4', 'Конкурсный каталог v4')], max_length=24)),
                ('row_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('kind', models.CharField(max_length=32)),
                ('type_label', models.CharField(blank=True, max_length=200)),
                ('subtype', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(max_length=32)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='catalog.catalogbatch')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_index', models.PositiveIntegerField()),
                ('line_start', models.PositiveIntegerField()),
                ('line_end', models.PositiveIntegerField()),
                ('external_id', models.CharField(max_length=100)),
                ('raw', models.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rows', to='catalog.catalogbatch')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rows', to='catalog.catalogfamily')),
            ],
            options={
                'ordering': ['record_index'],
            },
        ),
        migrations.CreateModel(
            name='CatalogOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=300)),
                ('price_raw', models.CharField(blank=True, max_length=100)),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_status', models.CharField(max_length=20)),
                ('currency_status', models.CharField(default='unknown', max_length=20)),
                ('vat_note', models.CharField(default='Статус НДС не подтверждён источником', max_length=100)),
                ('source_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='catalog.catalogsourcerow')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField()),
                ('cases', models.TextField()),
                ('industry', models.CharField(max_length=200)),
                ('market_potential_raw', models.CharField(blank=True, max_length=100)),
                ('source_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='catalog.catalogsourcerow')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.JSONField(default=dict)),
                ('status', models.CharField(default='missing', max_length=20)),
                ('source_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='catalog.catalogsourcerow')),
            ],
        ),
        migrations.AddConstraint(
            model_name='catalogfamily',
            constraint=models.UniqueConstraint(fields=('batch', 'identity_key'), name='unique_catalog_family_in_batch'),
        ),
        migrations.AddConstraint(
            model_name='catalogsourcerow',
            constraint=models.UniqueConstraint(fields=('batch', 'record_index'), name='unique_catalog_source_record'),
        ),
    ]
