# Generated by Django 5.2.17 on 2026-09-24 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEvidenceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('source_label', models.CharField(max_length=100)),
                ('claim_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_batches', to='catalog.catalogbatch')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogEvidenceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=120)),
                ('object_slug', models.CharField(max_length=32)),
                ('attribute', models.CharField(max_length=120)),
                ('value', models.JSONField(blank=True, null=True)),
                ('unit', models.CharField(max_length=80)),
                ('scope', models.TextField()),
                ('status', models.CharField(max_length=40)),
                ('use', models.CharField(max_length=40)),
                ('source_url', models.URLField(max_length=1000)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_fetched_at_utc', models.DateTimeField()),
                ('catalog_rows', models.ManyToManyField(blank=True, related_name='evidence_claims', to='catalog.catalogsourcerow')),
                ('evidence_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='catalog.catalogevidencebatch')),
            ],
            options={
                'ordering': ['claim_id'],
                'constraints': [models.UniqueConstraint(fields=('evidence_batch', 'claim_id'), name='unique_evidence_claim_in_batch')],
            },
        ),
    ]
