# Generated by Django 5.2.17 on 2026-09-26 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogevidencebatch_catalogevidenceclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogbatch',
            name='raw_source',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='catalogevidencebatch',
            name='raw_source',
            field=models.BinaryField(null=True),
        ),
        migrations.CreateModel(
            name='CatalogImportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('source_kind', models.CharField(choices=[('catalog', 'Каталог'), ('evidence', 'Первичные сведения')], max_length=16)),
                ('checksum', models.CharField(max_length=64)),
                ('source_label', models.CharField(max_length=100)),
                ('rights_basis', models.CharField(max_length=500)),
                ('created_new', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
