# Generated by Django 5.2.17 on 2026-09-26 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def pin_existing_evidence(apps, schema_editor):
    evidence = apps.get_model('catalog', 'CatalogEvidenceBatch').objects.order_by(
        '-created_at', '-pk',
    ).first()
    if evidence:
        apps.get_model('catalog', 'CatalogPublication').objects.create(
            key='storefront', evidence_batch_id=evidence.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogbatch_raw_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPublication',
            fields=[
                ('key', models.CharField(default='storefront', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('selected_at', models.DateTimeField(auto_now=True)),
                ('evidence_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogevidencebatch')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPublicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('previous_checksum', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogevidencebatch')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(pin_existing_evidence, migrations.RunPython.noop),
    ]
