# Generated by Django 5.2.17 on 2026-09-26 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalogpublication_catalogpublicationevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('source_label', models.CharField(max_length=100)),
                ('rights_basis', models.CharField(max_length=500)),
                ('raw_source', models.BinaryField()),
                ('product_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('import', 'Импорт'), ('publish', 'Публикация')], max_length=16)),
                ('actor_name', models.CharField(max_length=150)),
                ('reason', models.CharField(max_length=500)),
                ('previous_checksum', models.CharField(blank=True, max_length=64)),
                ('created_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.supplementbatch')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplementPublication',
            fields=[
                ('key', models.CharField(default='storefront', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('selected_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.supplementbatch')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementSourceArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ref', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('checksum', models.CharField(max_length=64)),
                ('fetched_at_utc', models.DateTimeField()),
                ('content_type', models.CharField(max_length=32)),
                ('raw_source', models.BinaryField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_artifacts', to='catalog.supplementbatch')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ref', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('variant', models.CharField(max_length=300)),
                ('product_url', models.URLField(max_length=1000)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.supplementbatch')),
                ('product_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.supplementsourceartifact')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_ref', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('vat_status', models.CharField(max_length=80)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.supplementproduct')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.supplementsourceartifact')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_slug', models.CharField(max_length=32)),
                ('process_code', models.CharField(max_length=80)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='catalog.supplementproduct')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.supplementsourceartifact')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=32)),
                ('source_value', models.CharField(max_length=100)),
                ('source_unit', models.CharField(max_length=32)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='catalog.supplementproduct')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.supplementsourceartifact')),
            ],
        ),
        migrations.AddConstraint(
            model_name='supplementsourceartifact',
            constraint=models.UniqueConstraint(fields=('batch', 'source_ref'), name='unique_supplement_source_ref'),
        ),
        migrations.AddConstraint(
            model_name='supplementproduct',
            constraint=models.UniqueConstraint(fields=('batch', 'product_ref'), name='unique_supplement_product_ref'),
        ),
        migrations.AddConstraint(
            model_name='supplementoffer',
            constraint=models.UniqueConstraint(fields=('product', 'offer_ref'), name='unique_supplement_offer_ref'),
        ),
        migrations.AddConstraint(
            model_name='supplementapplication',
            constraint=models.UniqueConstraint(fields=('product', 'process_code'), name='unique_supplement_application'),
        ),
    ]
