# Generated by Django 5.2.17 on 2026-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_supplementbatch_supplementauditevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementoffer',
            name='kind',
            field=models.CharField(choices=[('', 'Не указан'), ('purchase', 'Покупка'), ('raas', 'RaaS'), ('rental', 'Аренда')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='supplementoffer',
            name='price_basis',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='supplementoffer',
            name='scope',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
